---
title: Package I Created 
author: Mary Lin
date: '2018-06-17'
slug: package-i-created
categories: []
tags: []
---

Me and my partner created a package to help with our entry in the Kaggle Competition. It is called Kaggler Help. The package provides two functions, one for replacing NAs in a column with the median of the column  and another to write out a csv file from a dataframe. 

This is the code for the replaceNansWithMedian function: 

replaceNansWithMedian <- function(df, colName) {
  colMedian <- median(df[[colName]], na.rm=TRUE)
  df[[colName]] <- tidyr::replace_na(df[[colName]], colMedian)
  return(df)
}

This is the code to write out the CSV file with a column of SK_ID_CURR and TARGET

writeCSV <- function(testdata, predictstatement, filename="yourAnswer") {
  fit2 <- data.frame(SK_ID_CURR = testdata$SK_ID_CURR, TARGET = predictstatement)
  write.csv(fit2, filename, row.names = FALSE, col.names = FALSE)
}

This package can be found on github @ https://github.com/marylin34/KaggleHelper/blob/master/R/writeCSV.R

It can be downloaded by running devtools::install_packages(jcreynol/KaggleHelper)